ADD CMake-3.20.1-GCCcore-10.3.0 to NESSI/2022.11
NorESSI/software-layer pull request #18
Opened 2023-02-14 19:04 UTC by TopRichard

2023-02-15 07:41 UTC, trz42 commented on EESSI-pilot-install-software.sh
>  ##### from https://github.com/easybuilders/easybuild-easyblocks/pull/2248
I suggest a small modification to the comment by removing four `####`. Thus becomes more readable and it will also be more easily comparable to what is used in the EESSI/software-layer repository. We don't need to rebuild as this is really more a change of style.

2023-02-15 07:43 UTC, trz42 requested changes
Looks good.

A minor change is required before we can ingest the built packages into the repository.

2023-02-15 09:10 UTC, TopRichard commented
The packages built by the bot have been successfully ingested.

2023-02-15 09:11 UTC, trz42 approved these changes

2023-02-15 09:12 UTC, merged

2023-02-16 12:19 UTC, TopRichard commented on EESSI-pilot-install-software.sh
>  ##### from https://github.com/easybuilders/easybuild-easyblocks/pull/2248
Done