Add Perl-5.32.1-GCCcore-10.3.0.eb to NESSI/2022.11
NorESSI/software-layer pull request #19
Opened 2023-02-15 14:57 UTC by TopRichard

Trying to add Perl-5.32.1-GCCcore-10.3.0.eb to NESSI/2022.11

2023-02-16 09:07 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Was there a specific reason to comment out building CMake?

2023-02-16 09:13 UTC, trz42 requested changes
Left a few comments. Maybe just clarifications are needed, maybe changes are needed. Will see.

2023-02-16 09:13 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +$EB Perl-5.32.1-GCCcore-10.3.0.eb --robot
There is a commented out line for Perl in the script. Should we use that one? Also includes some additional parameters.

2023-02-16 09:13 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Was there a specific reason to comment out building CMake?

2023-02-16 09:13 UTC, trz42 commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
Any specific reason to remove CMake from the easy stack file?

Also, we might have forgotten to add the parameter `--include-easyblocks-from-pr 2248` here (in the PR that got merged, my fault for not spotting it earlier). We should make a small PR before merging the others to get this fixed.

2023-02-16 09:16 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
It is already built and present in the CernVM-FS.

2023-02-16 09:23 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +$EB Perl-5.32.1-GCCcore-10.3.0.eb --robot
Yep, I will create a new pull request using the one within the script.

2023-02-16 09:25 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Hmm, that's not a reason to comment it out. If it is present, we *can* comment it out, but we should only do so if there is a good reason (such as hitting the rate limit issue).

Can you change it and rebuild?

2023-02-16 09:28 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
sure

2023-02-16 12:14 UTC, TopRichard commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
Followed the new guidelines and added it back

2023-02-16 15:12 UTC, trz42 commented
The Fram jobs have been canceled. So need to rebuild them. Unsetting/setting `bot:build` label.

2023-02-21 08:46 UTC, trz42 commented
For the time being we ignore the build jobs on `AWS-NESSI`.

@TopRichard Some of the tarballs have a reasonable size, some seem to not contain anything/much. Could you investigate the reason(s)?

2023-02-22 10:24 UTC, trz42 commented
The software was a dependency of #20 which has already been ingested. Hence, we close this here.

2023-02-22 10:24 UTC, closed without merging