Add Python-3.9.5-GCCcore-10.3.0-bare.eb to NESSI/2022.11
NorESSI/software-layer pull request #20
Opened 2023-02-15 16:42 UTC by TopRichard

Trying to add Python-3.9.5-GCCcore-10.3.0-bare.eb to NESSI/2022.11

2023-02-16 09:21 UTC, trz42 requested changes
Left a few comments.

2023-02-16 09:21 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Any reason to comment this out?

2023-02-16 09:21 UTC, trz42 commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
Why removing it from the easystack file?

2023-02-16 09:21 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +$EB Python-3.9.5-GCCcore-10.3.0-bare.eb --robot
Wondering a bit about the specific easyconfig `-bare` suffix being used. Are there others (without the suffix)? If so why was this chosen?

2023-02-16 09:21 UTC, trz42 commented on eessi-2022.11.yml
> +  - Python-3.9.5-GCCcore-10.3.0-bare.eb
See comment about suffix `-bare`.

2023-02-16 09:44 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +$EB Python-3.9.5-GCCcore-10.3.0-bare.eb --robot
Couldn't find in (easybuild-easyconfigs) other than that for version 10.3.0, any suggestions?

2023-02-16 11:36 UTC, TopRichard commented on eessi-2022.11.yml
> +  - Python-3.9.5-GCCcore-10.3.0-bare.eb
Followed the guide lines.

2023-02-16 11:39 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +$EB Python-3.9.5-GCCcore-10.3.0-bare.eb --robot
Found the Python version WITHOUT the bare- after assistance, now it is just Python-3.9.5-GCCcore-10.3.0

2023-02-16 11:42 UTC, TopRichard commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
Added it back and followed the guidelines

2023-02-16 12:12 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Followed the new guidelines and added it back

2023-02-16 17:23 UTC, trz42 commented
Build for `skylake_avx512` failed. Checking on the build cluster (Saga) it seemed as this might have been just a temporary/local issue (builds for `cascadelake` and `generic` succeeded). We retrigger the build hoping it works out this time.

2023-02-16 23:32 UTC, trz42 commented
All built and looking good. Starting ingestion procedure.

2023-02-16 23:32 UTC, trz42 approved these changes

2023-02-17 00:04 UTC, trz42 commented
All ingested and available online. Ready to merge.

2023-02-17 00:05 UTC, merged