{2023.06}[foss/2022a] Pillow V9.1.1
NorESSI/software-layer pull request #202
Opened 2023-10-10 12:35 UTC by TopRichard

The actual build issue with Pillow is that it can't find zlib through the  hardcoded paths, the problem is solved by using --disable-platform-guessing (which was introduced in https://github.com/easybuilders/easybuild-easyconfigs/pull/18881), and adding the appropriate paths to $CPATH and $LIBRARY_PATH via a hook.

2023-10-10 12:36 UTC, TopRichard commented
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

2023-10-11 07:46 UTC, trz42 requested changes
Looks good overall. Some suggestions to keep the overall design of the hooks file consistent.

Instead of setting the envvars, the EESSI_* paths should be added. Otherwise, existing values could be overwritten.

2023-10-11 07:46 UTC, trz42 commented on eb_hooks.py
> +def set_Pillow_envvars(ec):
Should be named similarly to the other `parse_hook`s and the arguments should have `eprefix` too, for example,

```python
def parse_hook_pillow_set_cpath_library_path(ec, eprefix):
```

The whole function should be moved to where it fits alphabetically (alphabetically ordered functions help in finding a function).

2023-10-11 07:46 UTC, trz42 commented on eb_hooks.py
> +    EESSI_LIB_PATH = os.getenv('EESSI_EPREFIX') + '/usr/lib64'
These two lines should probably be moved inside the `if` block?

2023-10-11 07:46 UTC, trz42 commented on eb_hooks.py
> +        os.environ['LIBRARY_PATH'] = os.pathsep + EESSI_LIB_PATH
These lines **set** the environment variables. The description of the PR says _adding_. I think it would be better to keep existing values, maybe something like the following could work

```python
os.environ['CPATH'] = os.pathsep.join(os.environ.get('CPATH', ''), EESSI_CPATH)
```

2023-10-11 07:46 UTC, trz42 commented on eb_hooks.py
> +        ec.log.info("NOTE: For Pillow which has Szip as a dependancy, LIBRARY_PATH has been set to %s", os.getenv('LIBRARY_PATH'))
Here `Szip` is mentioned while earlier not finding `zlib` was the problem.

The messages could be a bit improved (particularly when adding directories), by stating something like

_original CPATH (OLD_VALUE) has been extended with EESSI_CPATH, new CPATH is NEW_VALUE_

or just

_CPATH (original value OLD_VALUE) has been extended with EESSI_CPATH_

2023-10-11 07:46 UTC, trz42 commented on eb_hooks.py
> +    set_Pillow_envvars(ec)
The new hook should be called via line (just 2 lines below where it is called now)

```python
PARSE_HOOKS[ec.name](ec, eprefix)
```

This requires that a line

```python
'Pillow': parse_hook_pillow_set_cpath_library_path,
```

is added to the `PARSE_HOOKS` dictionary (near the end of the file).

2023-10-11 07:46 UTC, trz42 commented on eessi-2023.06-eb-4.8.1-2022a.yml
> +      # Uses a custom hook since has Szip as dependency which has hard coded header and library path within Pillow code.
Is it `Szip` or `zlib`?

2023-10-11 07:47 UTC, trz42 commented on eb_hooks.py
> +        os.environ['LIBRARY_PATH'] = os.pathsep + EESSI_LIB_PATH
If this works, could be checked in an interactive Python session.

2023-10-11 07:54 UTC, TopRichard commented on eb_hooks.py
> +        os.environ['LIBRARY_PATH'] = os.pathsep + EESSI_LIB_PATH
I am setting the CPATH, but adding to the existing CPATH value.

2023-10-11 07:57 UTC, TopRichard commented on eb_hooks.py
> +        ec.log.info("NOTE: For Pillow which has Szip as a dependancy, LIBRARY_PATH has been set to %s", os.getenv('LIBRARY_PATH'))
Pillow required Szip which in turn requires zlib, i will modify the messages to make things clearer.

2023-10-11 08:01 UTC, trz42 commented on eb_hooks.py
> +        os.environ['LIBRARY_PATH'] = os.pathsep + EESSI_LIB_PATH
The following could work

```python
os.environ['CPATH'] = os.pathsep.join(filter(None,[os.environ.get('CPATH',''), EESSI_CPATH]))
```

2023-10-11 08:04 UTC, TopRichard commented on eessi-2023.06-eb-4.8.1-2022a.yml
> +      # Uses a custom hook since has Szip as dependency which has hard coded header and library path within Pillow code.
100%, will fix

2023-10-11 08:06 UTC, trz42 commented on eb_hooks.py
> +        os.environ['LIBRARY_PATH'] = os.pathsep + EESSI_LIB_PATH
> I am setting the CPATH, but adding to the existing CPATH value, yet we can set whichever suits best.

`CPATH` may already be set to some value. If so it would be overwritten. That could lead then to other issues difficult to debug.

2023-10-11 10:12 UTC, trz42 requested changes
Few additional suggestions.

2023-10-11 10:12 UTC, trz42 commented on eb_hooks.py
> +    """Get EESSI_CPATH environment variable from the environment"""
Actually, the hook augments env vars `CPATH` and `LIBRARY_PATH` with paths including the EESSI_PREFIX.

Mention `LIBRARY_PATH` too?

2023-10-11 10:12 UTC, trz42 commented on eb_hooks.py
> +                    os.getenv('LIBRARY_PATH'), EESSI_LIB_PATH)
Minor suggestion on formatting. Added spaces.

```python
"NOTE: Pillow has zlib as a dependency. The original CPATH ..."
```

2023-10-11 10:12 UTC, trz42 commented on eb_hooks.py
> +    'Pillow': parse_hook_pillow_set_cpath_library_path,
Could you order the entries alphabetically ... one line upwards.

2023-10-11 10:12 UTC, trz42 commented on eb_hooks.py
> +def parse_hook_pillow_set_cpath_library_path(ec, eprefix):
Could you move the whole function to where the other parse hooks are defined?

2023-10-11 10:43 UTC, TopRichard commented on eb_hooks.py
> +    """Get EESSI_CPATH environment variable from the environment"""
Does this look good : Extend CPATH and LIBRARY_PATH environment variables using EESSI_EPREFIX.

2023-10-11 12:41 UTC, trz42 approved these changes

2023-10-11 12:46 UTC, TopRichard commented
Checklist for building Pillow V9.1.1: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- []  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
Pillow can't find zlib through the hardcoded paths, the problem is solved using --disable-platform-guessing and adding the appropriate paths to $CPATH and $LIBRARY_PATH via a hook.

2023-10-11 13:17 UTC, TopRichard commented
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Pillow/9.1.1-GCCcore-11.3.0* \
        aarch64/generic/{software,modules/all}/Pillow/9.1.1-GCCcore-11.3.0*
  ```
-rw-r--r--. 1 cvmfs cvmfs 1600 Oct 10 12:43 aarch64/generic/modules/all/Pillow/9.1.1-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1600 Oct 10 12:47 x86_64/amd/zen2/modules/all/Pillow/9.1.1-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1599 Oct 10 12:54 x86_64/generic/modules/all/Pillow/9.1.1-GCCcore-11.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1607 Oct 10 12:39 x86_64/intel/broadwell/modules/all/Pillow/9.1.1-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1609 Oct 10 12:54 x86_64/intel/cascadelake/modules/all/Pillow/9.1.1-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1612 Oct 10 12:54 x86_64/intel/skylake_avx512/modules/all/Pillow/9.1.1-GCCcore-11.3.0.lua

aarch64/generic/software/Pillow/9.1.1-GCCcore-11.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:43 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:41 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 10 12:42 lib64 -> lib

x86_64/amd/zen2/software/Pillow/9.1.1-GCCcore-11.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:47 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:45 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 10 12:47 lib64 -> lib

x86_64/generic/software/Pillow/9.1.1-GCCcore-11.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:54 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 10 12:54 lib64 -> lib

x86_64/intel/broadwell/software/Pillow/9.1.1-GCCcore-11.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:39 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:38 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 10 12:39 lib64 -> lib

x86_64/intel/cascadelake/software/Pillow/9.1.1-GCCcore-11.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:54 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 10 12:54 lib64 -> lib

x86_64/intel/skylake_avx512/software/Pillow/9.1.1-GCCcore-11.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:54 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 10 12:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 10 12:54 lib64 -> lib
```
</details>

2023-10-11 13:28 UTC, merged