Add Ruby-GCCcore-10.3.0.eb to NESSI/2022.11
NorESSI/software-layer pull request #21
Opened 2023-02-16 08:27 UTC by TopRichard

Trying to add Ruby-GCCcore-10.3.0.eb to NESSI/2022.11

2023-02-16 09:34 UTC, trz42 requested changes
Left a few comments.

2023-02-16 09:34 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Lets keep it uncommented for the moment.

2023-02-16 09:34 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +$EB Ruby-3.0.1-GCCcore-10.3.0.eb --robot
Just curious, why was Ruby considered?

2023-02-16 09:34 UTC, trz42 commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
I'd leave CMake in the easy stack file.

2023-02-16 11:14 UTC, TopRichard commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
Done

2023-02-16 11:14 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +#$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Done

2023-02-16 12:11 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +$EB Ruby-3.0.1-GCCcore-10.3.0.eb --robot
No specific reason

2023-02-16 14:56 UTC, trz42 commented
Builds for Fram are missing in the last batch. We may want to retry this later on.

2023-02-21 09:08 UTC, trz42 commented
@TopRichard could you investigate why the builds on Fram failed? Maybe a temporary issue. Might be ok/easiest, to just retrigger the builds and only investigate if the problem persists.

2023-08-04 07:31 UTC, closed without merging