{2023.06}[system] EasyBuild V4.8.2
NorESSI/software-layer pull request #212
Opened 2023-10-30 11:18 UTC by TopRichard

Adds EasyBuild 4.8.2 via a new easystack file for the system toolchain, also excludes CI test for **aarch64** and **cascadelake**.

2023-10-30 11:23 UTC, TopRichard commented
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

2023-10-30 12:12 UTC, TopRichard commented
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

2023-10-30 12:43 UTC, TopRichard commented
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2

2023-10-30 13:53 UTC, TopRichard commented
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

2023-10-30 14:13 UTC, TopRichard commented
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

2023-10-30 14:26 UTC, TopRichard commented
Checklist for building EasyBuild 4.8.2: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- []  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

2023-11-02 09:29 UTC, trz42 requested changes
Small, easy to fix glitch in CI file.

Next time, I think it's better to not do side-effects in a PR (disabling testing for `aarch64/generic` and `cascadelake`). We can keep the change in here, though.

2023-11-02 09:29 UTC, trz42 commented on .github/workflows/test_eessi.yml
> +        - eessi-2023.06-eb-4.8.2-system.yml
There is no such file yet. So this should be removed. EB v4.8.2 is added via `eessi-2023.06-eb-4.8.1-system.yml`

2023-11-02 09:30 UTC, trz42 commented
Instance on eX3 is running again.

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

2023-11-02 10:30 UTC, TopRichard commented on .github/workflows/test_eessi.yml
> +        - eessi-2023.06-eb-4.8.2-system.yml
Residue of earlier mistake.

2023-11-02 11:53 UTC, TopRichard commented
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

2023-11-02 12:26 UTC, TopRichard commented
Checklist for building EasyBuild V4.8.2 : 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- []  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

2023-11-02 13:05 UTC, TopRichard commented
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] the PR has a license info for the ingested software
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/4.8.2* \
        aarch64/generic/{software,modules/all}/EasyBuild/4.8.2*
        
  -rw-r--r--. 1 cvmfs cvmfs 1223 Nov  2 12:04 aarch64/generic/modules/all/EasyBuild/4.8.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1222 Oct 30 14:22 x86_64/amd/zen2/modules/all/EasyBuild/4.8.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1221 Oct 30 14:04 x86_64/generic/modules/all/EasyBuild/4.8.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1229 Oct 30 14:19 x86_64/intel/broadwell/modules/all/EasyBuild/4.8.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1234 Oct 30 14:19 x86_64/intel/skylake_avx512/modules/all/EasyBuild/4.8.2.lua

aarch64/generic/software/EasyBuild/4.8.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  2 12:03 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  2 12:03 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Nov  2 12:06 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  2 12:03 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  2 12:02 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Nov  2 12:04 lib64 -> lib

x86_64/amd/zen2/software/EasyBuild/4.8.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:21 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:21 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct 30 14:23 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 30 14:21 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:21 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 30 14:22 lib64 -> lib

x86_64/generic/software/EasyBuild/4.8.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:04 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:04 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct 30 14:05 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 30 14:04 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:03 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 30 14:04 lib64 -> lib

x86_64/intel/broadwell/software/EasyBuild/4.8.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:18 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:18 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct 30 14:20 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 30 14:18 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:18 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 30 14:19 lib64 -> lib

x86_64/intel/skylake_avx512/software/EasyBuild/4.8.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:18 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:18 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct 30 14:21 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 30 14:18 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 30 14:18 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 30 14:19 lib64 -> lib
```
</details>

2023-11-02 21:10 UTC, trz42 approved these changes

2023-11-02 21:11 UTC, trz42 commented
All ingested successfully. CI turned green. Changes are sound. :+1:

2023-11-02 21:11 UTC, merged