Modifying directory structure + drop pilot terminology
NorESSI/software-layer pull request #217
Opened 2024-01-11 12:43 UTC by TopRichard

Trying to get closer to EESSI by modifying the directory structure and applying modifications done in [PR](https://github.com/EESSI/software-layer/pull/387)

2024-01-15 14:19 UTC, trz42 requested changes
Looks mostly good. Left a few comments.

I'm a bit uncertain about the changes related to `archdetect`. To be on the safe side we would have to build for all architectures we need or at least those that are different from EESSI.

2024-01-15 14:19 UTC, trz42 commented on README.md
> +Using x86_64/intel/haswell subdirectory for software layer
Maybe `(HARDCODED)` was wrong? I think, this is just an example output. So maybe good to check what we get on a client, then use that?

2024-01-15 14:19 UTC, trz42 commented on README.md
> +Found EESSI repo @ /cvmfs/software.eessi.io/versions/2023.06!
This is a bit tricky as it is the result of what is in the CVMFS repository. Maybe check what it is now and use that? In case we change the CVMFS repository side, we only need to remember to change it here too.

2024-01-15 14:19 UTC, trz42 commented on README.md
> +[EESSI 2023.06] $
This is a bit tricky as it is the result of what is in the CVMFS repository. Maybe check what it is now and use that? In case we change the CVMFS repository side, we only need to remember to change it here too.

2024-01-15 14:19 UTC, trz42 commented on init/eessi_defaults
> +# export EESSI_CVMFS_REPO="${EESSI_CVMFS_REPO_OVERRIDE:=/cvmfs/pilot.nessi.no}"
I think, we need to keep `/cvmfs/pilot.nessi.no` here.

2024-01-15 17:05 UTC, TopRichard commented on init/eessi_defaults
> +# export EESSI_CVMFS_REPO="${EESSI_CVMFS_REPO_OVERRIDE:=/cvmfs/pilot.nessi.no}"
keeping /cvmfs/pilot.nessi.no results in failing CI tests.

2024-01-15 17:49 UTC, TopRichard commented on README.md
> +Found EESSI repo @ /cvmfs/software.eessi.io/versions/2023.06!
Check last two commits, keeping it as /cvmfs/pilot.nessi.no results in failing CI tests.

2024-01-16 07:32 UTC, TopRichard commented
When changing the README.md only without the init/eessi_defaults file to default, the CI Tests for consistency of README.md fails with :
```
Run source init/eessi_defaults
  source init/eessi_defaults
  grep "${EESSI_CVMFS_REPO}" README.md
  shell: /usr/bin/bash -e {0}
Error: Process completed with exit code 1.
```

2024-01-16 13:37 UTC, trz42 approved these changes
Lets merge it and see if it/what works.

2024-01-16 13:37 UTC, merged