Add IPython-7.25.0-GCCcore-10.3.0.eb to NESSI/2022.11
NorESSI/software-layer pull request #22
Opened 2023-02-16 09:10 UTC by TopRichard

Trying to add IPython-7.25.0-GCCcore-10.3.0.eb to NESSI/2022.11

2023-02-16 09:39 UTC, trz42 requested changes
Minor comments.

2023-02-16 09:39 UTC, trz42 commented on EESSI-pilot-install-software.sh
> -$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Let's keep CMake uncommented.

2023-02-16 09:39 UTC, trz42 commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
Let's keep it in the easystack file.

2023-02-16 11:53 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> -$EB CMake-3.20.1-GCCcore-10.3.0.eb --robot --include-easyblocks-from-pr 2248
Followed the guidelines

2023-02-16 11:53 UTC, TopRichard commented on eessi-2022.11.yml
> -  - CMake-3.20.1-GCCcore-10.3.0.eb
Followed the guidelines

2023-02-21 09:26 UTC, trz42 commented
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - succeeded for `x86_64/generic`, `x86_64/amd/zen2`, `x86_64/intel/{broadwell,skylake_avx512,cascadelake}`
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [ ] are all requested changes sound (checking files changed on GitHub.com)
  - it seems something from a merge conflict has leaked into `EESSI-pilot-install-software.sh`
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
  - included with EB v4.7.0
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - no changes were needed

2023-02-21 09:30 UTC, trz42 requested changes
Minor tweak in easystack file needed.

2023-02-21 09:30 UTC, trz42 commented on eessi-2022.11.yml
>    - Python-3.9.5-GCCcore-10.3.0.eb
Should the order be

```ini
  - Python-3.9.5-GCCcore-10.3.0.eb
  - IPython-7.25.0-GCCcore-10.3.0.eb
```

Seems more logical to build Python first, then IPython?

2023-02-22 23:20 UTC, trz42 commented
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

@TopRichard nearly done! The order of `eb` files in `EESSI-pilot-install-software.sh` and `eessi-2022.11.yml` should be consistent. That's an easy fix, no need to rebuild. Other than that, the software is ready to get deployed.

2023-08-04 07:32 UTC, closed without merging