Add fix for permissions set on Lmod SitePackage and fixed spacing
NorESSI/software-layer pull request #342
Opened 2024-04-30 08:33 UTC by TopRichard

Follow up with  https://github.com/EESSI/software-layer/pull/538
This PR fixes an issue by setting 664 permissions after the file is created.

2024-04-30 08:37 UTC, TopRichard commented
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

2024-04-30 12:48 UTC, trz42 requested changes
Small improvement suggested.

2024-04-30 12:48 UTC, trz42 commented on create_lmodsitepackage.py
> +
Adds whitespace in this line. Should be removed.

2024-04-30 13:25 UTC, TopRichard commented
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

2024-04-30 21:39 UTC, TopRichard commented
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - only a code update
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  -  no easyconfig is used
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

2024-04-30 22:07 UTC, TopRichard commented
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
  - only code
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - one test failure, will ignore for now
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
ls -l \
      x86_64/{generic,amd/zen2,intel/[bsc]*}/.lmod/SitePackage.lua \
      aarch64/generic/.lmod/SitePackage.lua
  ```
  **log**
```
-rw-rw-r--. 1 cvmfs cvmfs 7197 Apr 30 15:27 aarch64/generic/.lmod/SitePackage.lua
-rw-rw-r--. 1 cvmfs cvmfs 7201 Apr 30 10:43 x86_64/amd/zen2/.lmod/SitePackage.lua
-rw-rw-r--. 1 cvmfs cvmfs 7201 Apr 30 10:44 x86_64/generic/.lmod/SitePackage.lua
-rw-rw-r--. 1 cvmfs cvmfs 7201 Apr 30 10:39 x86_64/intel/broadwell/.lmod/SitePackage.lua
-rw-rw-r--. 1 cvmfs cvmfs 7201 Apr 30 10:40 x86_64/intel/skylake_avx512/.lmod/SitePackage.lua
```
</details>

2024-04-30 22:09 UTC, justadejavu approved these changes
lgtm

2024-05-01 18:40 UTC, trz42 approved these changes
lgtm

2024-05-01 18:41 UTC, merged