Add latest EasyBuild release to NESSI/2022.11
NorESSI/software-layer pull request #5
Opened 2023-02-06 10:19 UTC by trz42

Another demo PR for illustrating the use of the EESSI bot.

2023-02-06 14:10 UTC, trz42 commented
Adding a comment. (check if bot instances receive event)

2023-02-06 14:14 UTC, trz42 commented
Next attempt.

2023-02-06 14:15 UTC, trz42 commented
One more.

2023-02-10 14:03 UTC, poksumdo commented on EESSI-pilot-install-software.sh
> +module --ignore_cache avail EasyBuild 2>&1 | grep EasyBuild
Clean up before merge.

2023-02-10 14:04 UTC, poksumdo commented on EESSI-pilot-install-software.sh
> +module --ignore_cache avail EasyBuild 2>&1 | grep EasyBuild
Cleanup before merge.

2023-02-10 14:07 UTC, poksumdo requested changes
Overall looks good.

Branch needs to be 
- [x] sync'ed,
- [ ] rebuilt, and
- [ ] reingested before it can be merged. That's because it was built not against the HEAD version of `nessi.no-2022.11-dev`.

Note, reingestion might require a reconfiguration of the bot instances to upload the `latest` tarballs (see option `upload_policy`).

- [x] Also additional printouts shall be removed or the output of the job would include unnecessary information.

2023-02-10 16:24 UTC, trz42 commented
Oh, packages are not really rebuilt because they are already in the stack. Instead of forcing to rebuild we remove EasyBuild from the stack (by rolling back the transactions on the Stratum0).

2023-02-10 17:58 UTC, poksumdo approved these changes

2023-02-10 18:13 UTC, trz42 commented
Only tarballs for NESSI/2022.11 will be ingested. Those for EESSI/2021.12 are rejected (because here we just test the builds for EESSI/2021.12 but we don't ingest).

2023-02-10 18:20 UTC, trz42 commented
All that needed to get ingested is available via CernVM-FS at a client. Ready to merge PR.

2023-02-10 18:20 UTC, merged