Add FlexiBlas/3.0.4 with GCC/10.3.0 to NESSI/2022.11
NorESSI/software-layer pull request #89
Opened 2023-03-28 10:53 UTC by TopRichard

Adding FlexiBlas/3.0.4 with GCC/10.3.0 to NESSI/2022.11 again to avoid all past failures and reviews

2023-04-20 09:03 UTC, TopRichard commented
bot: build I:AWS A:x86_64/generic R:11
bot: build I:AWS A:x86_64/intel/cascadelake R:11
bot: build I:AWS A:x86_64/intel/skylake R:11
bot: build I:Fram-NESSI A:x86_64/intel/broadwell R:11
bot: build I:eX3 A:zen2 R:11
bot: build I:eX3 A:aarch64/generic R:11

2023-04-20 09:08 UTC, TopRichard commented
bot: build inst:AWS arch:x86_64/generic repo:11
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:11
bot: build inst:AWS arch:x86_64/intel/skylake repo:11
bot: build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:11
bot: build inst:eX3 arch:zen2 repo:11
bot: build inst:eX3 arch:aarch64/generic repo:11

2023-04-21 05:27 UTC, trz42 requested changes
Looks good. Small change is needed before merging.

2023-04-21 05:27 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +    check_exit_code $? "${ok_msg}" "${fail_msg}"
Before merging this line should be moved outside the if/fi block or the result of building for ppc64le/generic would not be checked.

2023-04-21 05:28 UTC, trz42 commented
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - don't know about the tarball size yet, due to changed format of PR comment
- [x]  is the PR up-to-date with the target branch nessi.no-2022.11-dev in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
  - Mostly yes. Small change is requested before merging. See https://github.com/NorESSI/software-layer/pull/89#pullrequestreview-1395072934
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - no changes were needed

2023-04-21 07:07 UTC, trz42 commented
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/FlexiBLAS/*
  ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/aarch64/generic/{software,modules/all}/FlexiBLAS/*
  ```
  **log**
  ```
  #ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/FlexiBLAS/*
   -rw-r--r--. 1 cvmfs cvmfs 1534 Apr 20 10:22 /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/amd/zen2/modules/all/FlexiBLAS/3.0.4-GCC-10.3.0.lua
  -rw-r--r--. 1 cvmfs cvmfs 1533 Apr 20 09:43 /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/generic/modules/all/FlexiBLAS/3.0.4-GCC-10.3.0.lua
  -rw-rw-r--. 1 cvmfs cvmfs 1541 Apr 20 12:02 /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/broadwell/modules/all/FlexiBLAS/3.0.4-GCC-10.3.0.lua
  -rw-r--r--. 1 cvmfs cvmfs 1543 Apr 20 09:35 /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/cascadelake/modules/all/FlexiBLAS/3.0.4-GCC-10.3.0.lua
  -rw-r--r--. 1 cvmfs cvmfs 1546 Apr 20 09:38 /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/skylake_avx512/modules/all/FlexiBLAS/3.0.4-GCC-10.3.0.lua

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/amd/zen2/software/FlexiBLAS/3.0.4-GCC-10.3.0:
  total 28
  drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 20 10:17 bin
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 10:22 easybuild
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 10:17 etc
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 10:17 include
  drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 20 10:22 lib
  lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 20 10:22 lib64 -> lib
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 10:17 share

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/generic/software/FlexiBLAS/3.0.4-GCC-10.3.0:
  total 28
  drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 20 09:40 bin
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:43 easybuild
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:40 etc
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:40 include
  drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 20 09:43 lib
  lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 20 09:43 lib64 -> lib
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:40 share

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/broadwell/software/FlexiBLAS/3.0.4-GCC-10.3.0:
  total 28
  drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 20 11:56 bin
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 12:02 easybuild
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 11:56 etc
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 11:56 include
  drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 20 12:02 lib
  lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 20 12:02 lib64 -> lib
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 11:56 share

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/cascadelake/software/FlexiBLAS/3.0.4-GCC-10.3.0:
  total 28
  drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 20 09:34 bin
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:35 easybuild
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:34 etc
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:34 include
  drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 20 09:35 lib
  lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 20 09:35 lib64 -> lib
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:34 share

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/skylake_avx512/software/FlexiBLAS/3.0.4-GCC-10.3.0:
  total 28
  drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 20 09:35 bin
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:38 easybuild
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:35 etc
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:35 include
  drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 20 09:37 lib
  lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 20 09:37 lib64 -> lib
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:35 share

  # ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/aarch64/generic/{software,modules/all}/FlexiBLAS/*
  -rw-r--r--. 1 cvmfs cvmfs 1534 Apr 20 10:05 /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/aarch64/generic/modules/all/FlexiBLAS/3.0.4-GCC-10.3.0.lua

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/aarch64/generic/software/FlexiBLAS/3.0.4-GCC-10.3.0:
  total 28
  drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 20 09:56 bin
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 10:06 easybuild
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:56 etc
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:56 include
  drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 20 10:05 lib
  lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 20 10:05 lib64 -> lib
  drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 20 09:56 share
  ```

2023-04-21 07:32 UTC, trz42 commented
Test if bots are still noisy?

2023-04-21 07:33 UTC, trz42 commented
bot: help

2023-04-21 07:35 UTC, trz42 approved these changes

2023-04-21 07:35 UTC, merged