Add HPCG/3.1 with GCC/10.3.0 to NESSI/2022.11
NorESSI/software-layer pull request #91
Opened 2023-04-04 13:02 UTC by TopRichard

Trying to add HPCG/3.1 with GCC/10.3.0 to NESSI/2022.11

2023-04-04 13:45 UTC, trz42 reviewed
Maybe the event was not forwarded from the smee server to the bot instances?

2023-04-04 13:45 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +#check_exit_code $exit_code "${ok_msg}" "${fail_msg}"
Any reason to leave lines 467-469 & 471 commented out?

2023-04-04 14:28 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +#check_exit_code $exit_code "${ok_msg}" "${fail_msg}"
left behind by mistake

2023-04-05 07:50 UTC, trz42 requested changes

2023-04-05 07:50 UTC, trz42 commented on EESSI-pilot-install-software.sh
> +check_exit_code $exit_code "${ok_msg}" "${fail_msg}"
`exit_code` is not set after the `$EB` command. Something like

```bash
exit_code=$?
```

is missing.

Alternatively, replace `$exit_code` with `$?`.

2023-04-05 08:01 UTC, TopRichard commented on EESSI-pilot-install-software.sh
> +check_exit_code $exit_code "${ok_msg}" "${fail_msg}"
Copied the syntax from Cadical, will replace and build again

2023-04-18 12:54 UTC, closed without merging